#!/usr/bin/env python3

import serial
import struct
import sys

def do8bit():
  try:
    while True:
      port = "/dev/ttyACM0"
      if len(sys.argv) == 2:
        port = sys.argv[1]

      c = serial.Serial(port=port, baudrate=9600)
      d = input("Insert any word: ")
      dd = f"{d}\n".encode()
      c.write(dd)
      print("Received: ", c.readline())
  except KeyboardInterrupt:
    c.close()


if __name__ == "__main__":
  do8bit()