#!/usr/bin/env python3

import serial
import struct


def do8bit():
  try:
    while True:
      c = serial.Serial(port="/dev/ttyACM0", baudrate=9600)
      d = input("Insert any word: ")
      dd = f"{d}\n".encode()
      c.write(dd)
      print("Received: ", c.readline())
  except KeyboardInterrupt:
    c.close()


if __name__ == "__main__":
  do8bit()