type
  VectorInterrupt* = enum
    Int0Vect = 1,
    Int1Vect,
    PCInt0Vect,
    PCInt1Vect,
    PCInt2Vect,
    WdtVect,
    Timer2CompAVect,
    Timer2CompBVect,
    Timer2OvfVect,
    Timer1CaptVect,
    Timer1CompAVect,
    Timer1CompBVect,
    Timer1OvfVect,
    Timer0CompAVect,
    Timer0CompBVect,
    Timer0OvfVect,
    SpiStcVect,
    Usart0RxVect,
    Usart0UdreVect,
    Usart0TxVect,
    AdcVect,
    EeReadyVect,
    AnalogCompVect,
    TwiVect,
    SpmReadyVect,

