type
  VectorInterrupt* = enum
    Int0Vect        = 1,
    Int1Vect        = 2,
    Timer1CaptVect  = 3,
    Timer1CompAVect = 4,
    Timer1CompBVect = 5,
    Timer1OvfVect   = 6,
    Timer0OvfVect   = 7,
    SpiStcVect      = 8,
    UsartRxVect     = 9,
    UsartUdreVect   = 10,
    UsartTxVect     = 11,
    AnaCompVect     = 12,
    Int2Vect        = 13,
    Timer0CompVect  = 14,
    EeRdyVect       = 15,
    SpmRdyVect      = 16,
