type
  VectorInterrupt* = enum
    Int0Vect   = 1
    Int1Vect,
    Int2Vect,
    Int3Vect,
    Int6Vect   = 7,
    PCInt0Vect = 9,
    USBGeneralVect,
    USBEndpointVect,
    WdtVect,
    Timer1CaptVect = 16,
    Timer1CompAVect,
    Timer1CompBVect,
    Timer1CompCVect,
    Timer1OvfVect,
    Timer0CompAVect,
    Timer0CompBVect,
    Timer0OvfVect,
    SpiStcVect,
    Usart1RxVect,
    Usart1UdreVect,
    Usart1TxVect,
    AnalogCompVect,
    AdcVect,
    EeReadyVect,
    Timer3CaptVect,
    Timer3CompAVect,
    Timer3CompBVect,
    Timer3CompCVect,
    Timer3OvfVect,
    TwiVect,
    SpmReadyVect,
    Timer4CompAVect,
    Timer4CompBVect,
    Timer4CompDVect,
    Timer4OvfVect,
    Timer4FpfVect,
