type
  VectorInterrupt* = enum
    ExtInt0Vect   = 1,
    PCInt0Vect    = 2,
    PCInt1Vect    = 3,
    WdtVect       = 4,
    Tim1CaptVect  = 5,
    Tim1CompAVect = 6,
    Tim1CompBVect = 7,
    Tim1OvfVect   = 8,
    Tim0CompAVect = 9,
    Tim0CompBVect = 10,
    Tim0OvfVect   = 11,
    AnaCompVect   = 12,
    AdcVect       = 13,
    EeRdyVect     = 14,
    UsiStrVect    = 15,
    UsiOvfVect    = 16,
