when defined(USING_ATMEGA4808):
  include interrupt/private/atmega4808
elif defined(USING_ATTINY806):
  include interrupt/private/attiny806
elif defined(USING_ATMEGA3290A):
  include interrupt/private/atmega3290a
elif defined(USING_ATMEGA16HVBREVB):
  include interrupt/private/atmega16hvbrevb
elif defined(USING_ATTINY807):
  include interrupt/private/attiny807
elif defined(USING_ATMEGA4809):
  include interrupt/private/atmega4809
elif defined(USING_ATMEGA3209):
  include interrupt/private/atmega3209
elif defined(USING_ATMEGA1608):
  include interrupt/private/atmega1608
elif defined(USING_ATTINY43U):
  include interrupt/private/attiny43u
elif defined(USING_ATMEGA168):
  include interrupt/private/atmega168
elif defined(USING_ATMEGA128RFA1):
  include interrupt/private/atmega128rfa1
elif defined(USING_ATMEGA1609):
  include interrupt/private/atmega1609
elif defined(USING_ATTINY804):
  include interrupt/private/attiny804
elif defined(USING_ATMEGA3208):
  include interrupt/private/atmega3208
elif defined(USING_ATMEGA64):
  include interrupt/private/atmega64
elif defined(USING_ATMEGA165PA):
  include interrupt/private/atmega165pa
elif defined(USING_ATMEGA48PB):
  include interrupt/private/atmega48pb
elif defined(USING_ATMEGA48):
  include interrupt/private/atmega48
elif defined(USING_ATMEGA88PB):
  include interrupt/private/atmega88pb
elif defined(USING_ATTINY828):
  include interrupt/private/attiny828
elif defined(USING_ATMEGA3290P):
  include interrupt/private/atmega3290p
elif defined(USING_ATTINY814):
  include interrupt/private/attiny814
elif defined(USING_ATTINY424):
  include interrupt/private/attiny424
elif defined(USING_ATMEGA325PA):
  include interrupt/private/atmega325pa
elif defined(USING_ATTINY48):
  include interrupt/private/attiny48
elif defined(USING_AT90CAN128):
  include interrupt/private/at90can128
elif defined(USING_ATMEGA88):
  include interrupt/private/atmega88
elif defined(USING_ATMEGA48PA):
  include interrupt/private/atmega48pa
elif defined(USING_ATMEGA88PA):
  include interrupt/private/atmega88pa
elif defined(USING_ATTINY4313):
  include interrupt/private/attiny4313
elif defined(USING_ATTINY817):
  include interrupt/private/attiny817
elif defined(USING_ATTINY426):
  include interrupt/private/attiny426
elif defined(USING_ATTINY427):
  include interrupt/private/attiny427
elif defined(USING_ATTINY816):
  include interrupt/private/attiny816
elif defined(USING_ATTINY88):
  include interrupt/private/attiny88
elif defined(USING_ATTINY261A):
  include interrupt/private/attiny261a
elif defined(USING_ATMEGAS64M1):
  include interrupt/private/atmegas64m1
elif defined(USING_ATTINY10):
  include interrupt/private/attiny10
elif defined(USING_ATMEGA128A):
  include interrupt/private/atmega128a
elif defined(USING_ATMEGA324P):
  include interrupt/private/atmega324p
elif defined(USING_ATMEGA64A):
  include interrupt/private/atmega64a
elif defined(USING_ATMEGA169A):
  include interrupt/private/atmega169a
elif defined(USING_ATTINY441):
  include interrupt/private/attiny441
elif defined(USING_ATMEGA164P):
  include interrupt/private/atmega164p
elif defined(USING_ATMEGA329A):
  include interrupt/private/atmega329a
elif defined(USING_ATMEGA48A):
  include interrupt/private/atmega48a
elif defined(USING_ATTINY11):
  include interrupt/private/attiny11
elif defined(USING_ATTINY1634):
  include interrupt/private/attiny1634
elif defined(USING_ATTINY24A):
  include interrupt/private/attiny24a
elif defined(USING_ATMEGA3250PA):
  include interrupt/private/atmega3250pa
elif defined(USING_ATTINY13):
  include interrupt/private/attiny13
elif defined(USING_ATMEGA1284):
  include interrupt/private/atmega1284
elif defined(USING_AT90CAN32):
  include interrupt/private/at90can32
elif defined(USING_ATMEGA128RFR2):
  include interrupt/private/atmega128rfr2
elif defined(USING_ATMEGA32C1):
  include interrupt/private/atmega32c1
elif defined(USING_ATTINY5):
  include interrupt/private/attiny5
elif defined(USING_ATMEGA328P):
  include interrupt/private/atmega328p
elif defined(USING_ATMEGA3290PA):
  include interrupt/private/atmega3290pa
elif defined(USING_AT90USB1286):
  include interrupt/private/at90usb1286
elif defined(USING_ATMEGA165A):
  include interrupt/private/atmega165a
elif defined(USING_ATMEGA644):
  include interrupt/private/atmega644
elif defined(USING_ATMEGA168P):
  include interrupt/private/atmega168p
elif defined(USING_ATMEGA645):
  include interrupt/private/atmega645
elif defined(USING_AT90USB1287):
  include interrupt/private/at90usb1287
elif defined(USING_ATMEGA64M1):
  include interrupt/private/atmega64m1
elif defined(USING_ATTINY4):
  include interrupt/private/attiny4
elif defined(USING_ATMEGA325A):
  include interrupt/private/atmega325a
elif defined(USING_ATMEGA6450A):
  include interrupt/private/atmega6450a
elif defined(USING_ATTINY12):
  include interrupt/private/attiny12
elif defined(USING_ATMEGA32HVBREVB):
  include interrupt/private/atmega32hvbrevb
elif defined(USING_ATMEGA2561):
  include interrupt/private/atmega2561
elif defined(USING_ATTINY1627):
  include interrupt/private/attiny1627
elif defined(USING_AT90USB162):
  include interrupt/private/at90usb162
elif defined(USING_ATTINY861A):
  include interrupt/private/attiny861a
elif defined(USING_ATTINY3226):
  include interrupt/private/attiny3226
elif defined(USING_ATMEGA1281):
  include interrupt/private/atmega1281
elif defined(USING_ATMEGA324A):
  include interrupt/private/atmega324a
elif defined(USING_ATMEGA325):
  include interrupt/private/atmega325
elif defined(USING_ATMEGA3290):
  include interrupt/private/atmega3290
elif defined(USING_ATTINY461A):
  include interrupt/private/attiny461a
elif defined(USING_ATMEGA169P):
  include interrupt/private/atmega169p
elif defined(USING_ATMEGA640):
  include interrupt/private/atmega640
elif defined(USING_ATTINY44A):
  include interrupt/private/attiny44a
elif defined(USING_ATMEGA164A):
  include interrupt/private/atmega164a
elif defined(USING_ATMEGA16HVA):
  include interrupt/private/atmega16hva
elif defined(USING_ATMEGA329P):
  include interrupt/private/atmega329p
elif defined(USING_ATTINY13A):
  include interrupt/private/attiny13a
elif defined(USING_ATMEGA48P):
  include interrupt/private/atmega48p
elif defined(USING_ATMEGA1280):
  include interrupt/private/atmega1280
elif defined(USING_ATMEGA16):
  include interrupt/private/atmega16
elif defined(USING_ATMEGA324PB):
  include interrupt/private/atmega324pb
elif defined(USING_ATTINY3227):
  include interrupt/private/attiny3227
elif defined(USING_ATMEGA8515):
  include interrupt/private/atmega8515
elif defined(USING_ATTINY2313):
  include interrupt/private/attiny2313
elif defined(USING_ATTINY1626):
  include interrupt/private/attiny1626
elif defined(USING_ATMEGA2560):
  include interrupt/private/atmega2560
elif defined(USING_ATTINY1624):
  include interrupt/private/attiny1624
elif defined(USING_ATMEGA32HVB):
  include interrupt/private/atmega32hvb
elif defined(USING_ATTINY15):
  include interrupt/private/attiny15
elif defined(USING_ATMEGA256RFR2):
  include interrupt/private/atmega256rfr2
elif defined(USING_ATMEGA164PA):
  include interrupt/private/atmega164pa
elif defined(USING_ATMEGA3250):
  include interrupt/private/atmega3250
elif defined(USING_ATMEGA165P):
  include interrupt/private/atmega165p
elif defined(USING_ATMEGA168A):
  include interrupt/private/atmega168a
elif defined(USING_ATMEGA16HVB):
  include interrupt/private/atmega16hvb
elif defined(USING_ATTINY861):
  include interrupt/private/attiny861
elif defined(USING_ATMEGA8U2):
  include interrupt/private/atmega8u2
elif defined(USING_ATMEGA32A):
  include interrupt/private/atmega32a
elif defined(USING_ATMEGA325P):
  include interrupt/private/atmega325p
elif defined(USING_ATMEGA6450P):
  include interrupt/private/atmega6450p
elif defined(USING_ATTINY3224):
  include interrupt/private/attiny3224
elif defined(USING_ATMEGA324PA):
  include interrupt/private/atmega324pa
elif defined(USING_ATTINY1614):
  include interrupt/private/attiny1614
elif defined(USING_ATTINY25):
  include interrupt/private/attiny25
elif defined(USING_ATTINY2313A):
  include interrupt/private/attiny2313a
elif defined(USING_ATMEGA64C1):
  include interrupt/private/atmega64c1
elif defined(USING_ATTINY461):
  include interrupt/private/attiny461
elif defined(USING_ATMEGA6490P):
  include interrupt/private/atmega6490p
elif defined(USING_ATMEGA128):
  include interrupt/private/atmega128
elif defined(USING_ATMEGA16M1):
  include interrupt/private/atmega16m1
elif defined(USING_ATMEGA168PA):
  include interrupt/private/atmega168pa
elif defined(USING_ATMEGA1284P):
  include interrupt/private/atmega1284p
elif defined(USING_ATMEGA32M1):
  include interrupt/private/atmega32m1
elif defined(USING_ATTINY104):
  include interrupt/private/attiny104
elif defined(USING_ATMEGA645A):
  include interrupt/private/atmega645a
elif defined(USING_ATTINY24):
  include interrupt/private/attiny24
elif defined(USING_ATMEGA328PB):
  include interrupt/private/atmega328pb
elif defined(USING_ATTINY1617):
  include interrupt/private/attiny1617
elif defined(USING_ATTINY26):
  include interrupt/private/attiny26
elif defined(USING_ATTINY3216):
  include interrupt/private/attiny3216
elif defined(USING_ATMEGA644P):
  include interrupt/private/atmega644p
elif defined(USING_ATMEGA16U4):
  include interrupt/private/atmega16u4
elif defined(USING_ATTINY84A):
  include interrupt/private/attiny84a
elif defined(USING_ATMEGA329):
  include interrupt/private/atmega329
elif defined(USING_AT90PWM2B):
  include interrupt/private/at90pwm2b
elif defined(USING_ATMEGA88P):
  include interrupt/private/atmega88p
elif defined(USING_ATMEGA32U4):
  include interrupt/private/atmega32u4
elif defined(USING_ATMEGA168PB):
  include interrupt/private/atmega168pb
elif defined(USING_ATMEGA328):
  include interrupt/private/atmega328
elif defined(USING_ATMEGA649A):
  include interrupt/private/atmega649a
elif defined(USING_ATTINY3217):
  include interrupt/private/attiny3217
elif defined(USING_ATMEGA32):
  include interrupt/private/atmega32
elif defined(USING_ATTINY1616):
  include interrupt/private/attiny1616
elif defined(USING_AT90PWM316):
  include interrupt/private/at90pwm316
elif defined(USING_ATTINY261):
  include interrupt/private/attiny261
elif defined(USING_ATTINY1606):
  include interrupt/private/attiny1606
elif defined(USING_ATMEGA8535):
  include interrupt/private/atmega8535
elif defined(USING_ATMEGA6450):
  include interrupt/private/atmega6450
elif defined(USING_ATMEGA1284RFR2):
  include interrupt/private/atmega1284rfr2
elif defined(USING_ATTINY9):
  include interrupt/private/attiny9
elif defined(USING_ATMEGA6490A):
  include interrupt/private/atmega6490a
elif defined(USING_ATMEGA649):
  include interrupt/private/atmega649
elif defined(USING_AT90PWM3B):
  include interrupt/private/at90pwm3b
elif defined(USING_ATMEGA645P):
  include interrupt/private/atmega645p
elif defined(USING_ATTINY102):
  include interrupt/private/attiny102
elif defined(USING_ATTINY1607):
  include interrupt/private/attiny1607
elif defined(USING_ATTINY20):
  include interrupt/private/attiny20
elif defined(USING_ATMEGA644A):
  include interrupt/private/atmega644a
elif defined(USING_ATMEGA644RFR2):
  include interrupt/private/atmega644rfr2
elif defined(USING_ATMEGA6490):
  include interrupt/private/atmega6490
elif defined(USING_ATMEGA16U2):
  include interrupt/private/atmega16u2
elif defined(USING_ATTINY841):
  include interrupt/private/attiny841
elif defined(USING_ATMEGA88A):
  include interrupt/private/atmega88a
elif defined(USING_ATMEGA32U2):
  include interrupt/private/atmega32u2
elif defined(USING_ATMEGA64HVE2):
  include interrupt/private/atmega64hve2
elif defined(USING_ATMEGA649P):
  include interrupt/private/atmega649p
elif defined(USING_ATTINY1604):
  include interrupt/private/attiny1604
elif defined(USING_ATTINY204):
  include interrupt/private/attiny204
elif defined(USING_AT90PWM161):
  include interrupt/private/at90pwm161
elif defined(USING_AT90PWM3):
  include interrupt/private/at90pwm3
elif defined(USING_ATTINY85):
  include interrupt/private/attiny85
elif defined(USING_ATTINY827):
  include interrupt/private/attiny827
elif defined(USING_ATTINY416):
  include interrupt/private/attiny416
elif defined(USING_ATTINY402):
  include interrupt/private/attiny402
elif defined(USING_ATMEGA162):
  include interrupt/private/atmega162
elif defined(USING_ATTINY417):
  include interrupt/private/attiny417
elif defined(USING_AT90PWM216):
  include interrupt/private/at90pwm216
elif defined(USING_ATMEGA406):
  include interrupt/private/atmega406
elif defined(USING_ATTINY826):
  include interrupt/private/attiny826
elif defined(USING_ATTINY167):
  include interrupt/private/attiny167
elif defined(USING_ATTINY84):
  include interrupt/private/attiny84
elif defined(USING_ATMEGA64RFR2):
  include interrupt/private/atmega64rfr2
elif defined(USING_ATTINY45):
  include interrupt/private/attiny45
elif defined(USING_ATMEGA8A):
  include interrupt/private/atmega8a
elif defined(USING_AT90CAN64):
  include interrupt/private/at90can64
elif defined(USING_ATMEGAS128):
  include interrupt/private/atmegas128
elif defined(USING_AT90USB82):
  include interrupt/private/at90usb82
elif defined(USING_ATTINY824):
  include interrupt/private/attiny824
elif defined(USING_ATMEGA8HVA):
  include interrupt/private/atmega8hva
elif defined(USING_ATMEGA329PA):
  include interrupt/private/atmega329pa
elif defined(USING_ATMEGA809):
  include interrupt/private/atmega809
elif defined(USING_ATTINY414):
  include interrupt/private/attiny414
elif defined(USING_ATMEGA3250P):
  include interrupt/private/atmega3250p
elif defined(USING_ATMEGA808):
  include interrupt/private/atmega808
elif defined(USING_ATTINY87):
  include interrupt/private/attiny87
elif defined(USING_AT90PWM1):
  include interrupt/private/at90pwm1
elif defined(USING_ATTINY44):
  include interrupt/private/attiny44
elif defined(USING_ATMEGA644PA):
  include interrupt/private/atmega644pa
elif defined(USING_ATMEGA169PA):
  include interrupt/private/atmega169pa
elif defined(USING_ATTINY212):
  include interrupt/private/attiny212
elif defined(USING_ATTINY202):
  include interrupt/private/attiny202
elif defined(USING_AT90USB646):
  include interrupt/private/at90usb646
elif defined(USING_ATMEGA2564RFR2):
  include interrupt/private/atmega2564rfr2
elif defined(USING_ATTINY40):
  include interrupt/private/attiny40
elif defined(USING_ATTINY404):
  include interrupt/private/attiny404
elif defined(USING_AT90PWM81):
  include interrupt/private/at90pwm81
elif defined(USING_AT90USB647):
  include interrupt/private/at90usb647
elif defined(USING_ATMEGA8):
  include interrupt/private/atmega8
elif defined(USING_ATMEGA16A):
  include interrupt/private/atmega16a
elif defined(USING_ATMEGA3250A):
  include interrupt/private/atmega3250a
elif defined(USING_ATTINY406):
  include interrupt/private/attiny406
elif defined(USING_ATTINY412):
  include interrupt/private/attiny412
elif defined(USING_ATTINY214):
  include interrupt/private/attiny214
else:
  static: error "undefined architecture"
