const
  PCMSK2* = MappedIoRegister[uint8](0x6D)
  UCSR2A* = MappedIoRegister[uint8](0xD0)
  UCSR2B* = MappedIoRegister[uint8](0XD1)
  UCSR2C* = MappedIoRegister[uint8](0xD2)
  UBRR2*  = MappedIoRegister[uint16](0xD4)
  UBRR2L* = MappedIoRegister[uint8](0xD4)
  UBRR2H* = MappedIoRegister[uint8](0xD5)
  UDR2*   = MappedIoRegister[uint8](0XD6)
  PINH*   = MappedIoRegister[uint8](0x100)
  DDRH*   = MappedIoRegister[uint8](0x101)
  PORTH*  = MappedIoRegister[uint8](0x102)
  PINJ*   = MappedIoRegister[uint8](0x103)
  DDRJ*   = MappedIoRegister[uint8](0x104)
  PORTJ*  = MappedIoRegister[uint8](0x105)
  PINK*   = MappedIoRegister[uint8](0x106)
  DDRK*   = MappedIoRegister[uint8](0x107)
  PORTK*  = MappedIoRegister[uint8](0x108)
  PINL*   = MappedIoRegister[uint8](0x109)
  DDRL*   = MappedIoRegister[uint8](0x10A)
  PORTL*  = MappedIoRegister[uint8](0x10B)
  UCSR3A* = MappedIoRegister[uint8](0x130)
  UCSR3B* = MappedIoRegister[uint8](0X131)
  UCSR3C* = MappedIoRegister[uint8](0x132)
  UBRR3*  = MappedIoRegister[uint16](0x134)
  UBRR3L* = MappedIoRegister[uint8](0x134)
  UBRR3H* = MappedIoRegister[uint8](0x135)
  UDR3*   = MappedIoRegister[uint8](0X136)

const
  portH* = Port(direction: DDRH, output: PORTH, input: PINH)
  portJ* = Port(direction: DDRJ, output: PORTJ, input: PINJ)
  portK* = Port(direction: DDRK, output: PORTK, input: PINK)
  portL* = Port(direction: DDRL, output: PORTL, input: PINL)
