include mapped_io
include usart
include timer

const
  TWBR*   = MappedIoRegister[uint8](0x20)
  TWSR*   = MappedIoRegister[uint8](0x21)
  TWAR*   = MappedIoRegister[uint8](0x22)
  TWDR*   = MappedIoRegister[uint8](0x23)
  ADC*    = MappedIoRegister[uint16](0x24)
  ADCL*   = MappedIoRegister[uint8](0x24)
  ADCH*   = MappedIoRegister[uint8](0x25)
  ADCSRA* = MappedIoRegister[uint8](0x26)
  ADMUX*  = MappedIoRegister[uint8](0x27)
  ACSR*   = MappedIoRegister[uint8](0x28)
  UBRRL*  = MappedIoRegister[uint8](0x29)
  UCSRB*  = MappedIoRegister[uint8](0x2A)
  UCSRA*  = MappedIoRegister[uint8](0x2B)
  UDR*    = MappedIoRegister[uint8](0x2C)
  SPCR*   = MappedIoRegister[uint8](0x2D)
  SPSR*   = MappedIoRegister[uint8](0x2E)
  SPDR*   = MappedIoRegister[uint8](0x2F)
  PIND*   = MappedIoRegister[uint8](0x30)
  DDRD*   = MappedIoRegister[uint8](0x31)
  PORTD*  = MappedIoRegister[uint8](0x32)
  PINC*   = MappedIoRegister[uint8](0x33)
  DDRC*   = MappedIoRegister[uint8](0x34)
  PORTC*  = MappedIoRegister[uint8](0x35)
  PINB*   = MappedIoRegister[uint8](0x36)
  DDRB*   = MappedIoRegister[uint8](0x37)
  PORTB*  = MappedIoRegister[uint8](0x38)
  PINA*   = MappedIoRegister[uint8](0x39)
  DDRA*   = MappedIoRegister[uint8](0x3A)
  PORTA*  = MappedIoRegister[uint8](0x3B)
  EECR*   = MappedIoRegister[uint8](0x3C)
  EEDR*   = MappedIoRegister[uint8](0x3D)
  EEAR*   = MappedIoRegister[uint16](0x3E)
  EEARL*  = MappedIoRegister[uint8](0x3E)
  EEARH*  = MappedIoRegister[uint8](0x3F)
  UCSRC*  = MappedIoRegister[uint8](0x40)
  UBRRH*  = MappedIoRegister[uint8](0x40)
  WDTCR*  = MappedIoRegister[uint8](0x41)
  ASSR*   = MappedIoRegister[uint8](0x42)
  OCR2*   = MappedIoRegister[uint8](0x43)
  TCNT2*  = MappedIoRegister[uint8](0x44)
  TCCR2*  = MappedIoRegister[uint8](0x45)
  ICR1*   = MappedIoRegister[uint16](0x46)
  ICR1L*  = MappedIoRegister[uint8](0x46)
  ICR1H*  = MappedIoRegister[uint8](0x47)
  OCR1B*  = MappedIoRegister[uint16](0x48)
  OCR1BL* = MappedIoRegister[uint8](0x48)
  OCR1BH* = MappedIoRegister[uint8](0x49)
  OCR1A*  = MappedIoRegister[uint16](0x4A)
  OCR1AL* = MappedIoRegister[uint8](0x4A)
  OCR1AH* = MappedIoRegister[uint8](0x4B)
  TCNT1*  = MappedIoRegister[uint16](0x4C)
  TCNT1L* = MappedIoRegister[uint8](0x4C)
  TCNT1H* = MappedIoRegister[uint8](0x4D)
  TCCR1B* = MappedIoRegister[uint8](0x4E)
  TCCR1A* = MappedIoRegister[uint8](0x4F)
  SFIOR*  = MappedIoRegister[uint8](0x50)
  OSCCAL* = MappedIoRegister[uint8](0x51)
  OCDR*   = MappedIoRegister[uint8](0x51)
  TCNT0*  = MappedIoRegister[uint8](0x52)
  TCCR0*  = MappedIoRegister[uint8](0x53)
  MCUCSR* = MappedIoRegister[uint8](0x54)
  MCUCR*  = MappedIoRegister[uint8](0x55)
  TWCR*   = MappedIoRegister[uint8](0x56)
  SPMCSR* = MappedIoRegister[uint8](0x57)
  TIFR*   = MappedIoRegister[uint8](0x58)
  TIMSK*  = MappedIoRegister[uint8](0x59)
  GIFR*   = MappedIoRegister[uint8](0x5A)
  GICR*   = MappedIoRegister[uint8](0x5B)
  OCR0*   = MappedIoRegister[uint8](0x5C)
  SP*     = MappedIoRegister[uint16](0x5D)
  SPL*    = MappedIoRegister[uint8](0x5D)
  SPH*    = MappedIoRegister[uint8](0x5E)
  SREG*   = MappedIoRegister[uint8](0x5F)

const
  porta* = Port(direction: DDRA, output: PORTA, input: PINA)
  portb* = Port(direction: DDRB, output: PORTB, input: PINB)
  portc* = Port(direction: DDRC, output: PORTC, input: PINC)
  portd* = Port(direction: DDRD, output: PORTD, input: PIND)

