include mapped_io
include usart
include timer

const
  PINB*   = MappedIoRegister[uint8](0x0)
  DDRB*   = MappedIoRegister[uint8](0x1)
  PORTB*  = MappedIoRegister[uint8](0x2)
  PUEB*   = MappedIoRegister[uint8](0x3)
  PORTCR* = MappedIoRegister[uint8](0xC)
  PCMSK*  = MappedIoRegister[uint8](0x10)
  PCIFR*  = MappedIoRegister[uint8](0x11)
  PCICR*  = MappedIoRegister[uint8](0x12)
  EIMSK*  = MappedIoRegister[uint8](0x13)
  EIFR*   = MappedIoRegister[uint8](0x14)
  EICRA*  = MappedIoRegister[uint8](0x15)
  DIDR0*  = MappedIoRegister[uint8](0x17)
  ACSR*   = MappedIoRegister[uint8](0x1F)
  ICR0*   = MappedIoRegister[uint16](0x22)
  ICR0L*  = MappedIoRegister[uint8](0x22)
  ICR0H*  = MappedIoRegister[uint8](0x23)
  OCR0B*  = MappedIoRegister[uint16](0x24)
  OCR0BL* = MappedIoRegister[uint8](0x24)
  OCR0BH* = MappedIoRegister[uint8](0x25)
  OCR0A*  = MappedIoRegister[uint16](0x26)
  OCR0AL* = MappedIoRegister[uint8](0x26)
  OCR0AH* = MappedIoRegister[uint8](0x27)
  TCNT0*  = MappedIoRegister[uint16](0x28)
  TCNT0L* = MappedIoRegister[uint8](0x28)
  TCNT0H* = MappedIoRegister[uint8](0x29)
  TIFR0*  = MappedIoRegister[uint8](0x2A)
  TIMSK0* = MappedIoRegister[uint8](0x2B)
  TCCR0C* = MappedIoRegister[uint8](0x2C)
  TCCR0B* = MappedIoRegister[uint8](0x2D)
  TCCR0A* = MappedIoRegister[uint8](0x2E)
  GTCCR*  = MappedIoRegister[uint8](0x2F)
  WDTCSR* = MappedIoRegister[uint8](0x31)
  NVMCSR* = MappedIoRegister[uint8](0x32)
  NVMCMD* = MappedIoRegister[uint8](0x33)
  VLMCSR* = MappedIoRegister[uint8](0x34)
  PRR*    = MappedIoRegister[uint8](0x35)
  CLKPSR* = MappedIoRegister[uint8](0x36)
  CLKMSR* = MappedIoRegister[uint8](0x37)
  OSCCAL* = MappedIoRegister[uint8](0x39)
  SMCR*   = MappedIoRegister[uint8](0x3A)
  RSTFLR* = MappedIoRegister[uint8](0x3B)
  CCP*    = MappedIoRegister[uint8](0x3C)
  SP*     = MappedIoRegister[uint16](0x3D)
  SPL*    = MappedIoRegister[uint8](0x3D)
  SPH*    = MappedIoRegister[uint8](0x3E)
  SREG*   = MappedIoRegister[uint8](0x3F)

const
  portb* = Port(direction: DDRB, output: PORTB, input: PINB)

