include mapped_io
include usart
include timer

const
  PRR*    = MappedIoRegister[uint8](0x20)
  DIDR0*  = MappedIoRegister[uint8](0x21)
  ADCSRB* = MappedIoRegister[uint8](0x23)
  ADC*    = MappedIoRegister[uint16](0x24)
  ADCL*   = MappedIoRegister[uint8](0x24)
  ADCH*   = MappedIoRegister[uint8](0x25)
  ADCSRA* = MappedIoRegister[uint8](0x26)
  ADMUX*  = MappedIoRegister[uint8](0x27)
  ACSR*   = MappedIoRegister[uint8](0x28)
  TIFR1*  = MappedIoRegister[uint8](0x2B)
  TIMSK1* = MappedIoRegister[uint8](0x2C)
  USICR*  = MappedIoRegister[uint8](0x2D)
  USISR*  = MappedIoRegister[uint8](0x2E)
  USIDR*  = MappedIoRegister[uint8](0x2F)
  USIBR*  = MappedIoRegister[uint8](0x30)
  PCMSK0* = MappedIoRegister[uint8](0x32)
  GPIOR0* = MappedIoRegister[uint8](0x33)
  GPIOR1* = MappedIoRegister[uint8](0x34)
  GPIOR2* = MappedIoRegister[uint8](0x35)
  PINB*   = MappedIoRegister[uint8](0x36)
  DDRB*   = MappedIoRegister[uint8](0x37)
  PORTB*  = MappedIoRegister[uint8](0x38)
  PINA*   = MappedIoRegister[uint8](0x39)
  DDRA*   = MappedIoRegister[uint8](0x3A)
  PORTA*  = MappedIoRegister[uint8](0x3B)
  EECR*   = MappedIoRegister[uint8](0x3C)
  EEDR*   = MappedIoRegister[uint8](0x3D)
  EEAR*   = MappedIoRegister[uint8](0x3E)
  PCMSK1* = MappedIoRegister[uint8](0x40)
  WDTCSR* = MappedIoRegister[uint8](0x41)
  GTCCR*  = MappedIoRegister[uint8](0x43)
  CLKPR*  = MappedIoRegister[uint8](0x46)
  OCR1B*  = MappedIoRegister[uint8](0x4B)
  OCR1A*  = MappedIoRegister[uint8](0x4C)
  TCNT1*  = MappedIoRegister[uint8](0x4D)
  TCCR1B* = MappedIoRegister[uint8](0x4E)
  TCCR1A* = MappedIoRegister[uint8](0x4F)
  TCCR0A* = MappedIoRegister[uint8](0x50)
  OSCCAL* = MappedIoRegister[uint8](0x51)
  TCNT0*  = MappedIoRegister[uint8](0x52)
  TCCR0B* = MappedIoRegister[uint8](0x53)
  MCUSR*  = MappedIoRegister[uint8](0x54)
  MCUCR*  = MappedIoRegister[uint8](0x55)
  OCR0A*  = MappedIoRegister[uint8](0x56)
  SPMCSR* = MappedIoRegister[uint8](0x57)
  TIFR0*  = MappedIoRegister[uint8](0x58)
  TIMSK0* = MappedIoRegister[uint8](0x59)
  GIFR*   = MappedIoRegister[uint8](0x5A)
  GIMSK*  = MappedIoRegister[uint8](0x5B)
  OCR0B*  = MappedIoRegister[uint8](0x5C)
  SP*     = MappedIoRegister[uint16](0x5D)
  SPL*    = MappedIoRegister[uint8](0x5D)
  SPH*    = MappedIoRegister[uint8](0x5E)
  SREG*   = MappedIoRegister[uint8](0x5F)

const
  porta* = Port(direction: DDRA, output: PORTA, input: PINA)
  portb* = Port(direction: DDRB, output: PORTB, input: PINB)

