include mapped_io
include usart
include timer

const
  DIDR*   = MappedIoRegister[uint8](0x21)
  UBRRH*  = MappedIoRegister[uint8](0x22)
  UCSRC*  = MappedIoRegister[uint8](0x23)
  PCMSK1* = MappedIoRegister[uint8](0x24)
  PCMSK2* = MappedIoRegister[uint8](0x25)
  PRR*    = MappedIoRegister[uint8](0x26)
  BODCR*  = MappedIoRegister[uint8](0x27)
  ACSR*   = MappedIoRegister[uint8](0x28)
  UBRRL*  = MappedIoRegister[uint8](0x29)
  UCSRB*  = MappedIoRegister[uint8](0x2A)
  UCSRA*  = MappedIoRegister[uint8](0x2B)
  UDR*    = MappedIoRegister[uint8](0x2C)
  USICR*  = MappedIoRegister[uint8](0x2D)
  USISR*  = MappedIoRegister[uint8](0x2E)
  USIDR*  = MappedIoRegister[uint8](0x2F)
  PIND*   = MappedIoRegister[uint8](0x30)
  DDRD*   = MappedIoRegister[uint8](0x31)
  PORTD*  = MappedIoRegister[uint8](0x32)
  GPIOR0* = MappedIoRegister[uint8](0x33)
  GPIOR1* = MappedIoRegister[uint8](0x34)
  GPIOR2* = MappedIoRegister[uint8](0x35)
  PINB*   = MappedIoRegister[uint8](0x36)
  DDRB*   = MappedIoRegister[uint8](0x37)
  PORTB*  = MappedIoRegister[uint8](0x38)
  PINA*   = MappedIoRegister[uint8](0x39)
  DDRA*   = MappedIoRegister[uint8](0x3A)
  PORTA*  = MappedIoRegister[uint8](0x3B)
  EECR*   = MappedIoRegister[uint8](0x3C)
  EEDR*   = MappedIoRegister[uint8](0x3D)
  EEAR*   = MappedIoRegister[uint8](0x3E)
  PCMSK0* = MappedIoRegister[uint8](0x40)
  WDTCR*  = MappedIoRegister[uint8](0x41)
  TCCR1C* = MappedIoRegister[uint8](0x42)
  GTCCR*  = MappedIoRegister[uint8](0x43)
  ICR1*   = MappedIoRegister[uint16](0x44)
  ICR1L*  = MappedIoRegister[uint8](0x44)
  ICR1H*  = MappedIoRegister[uint8](0x45)
  CLKPR*  = MappedIoRegister[uint8](0x46)
  OCR1B*  = MappedIoRegister[uint16](0x48)
  OCR1BL* = MappedIoRegister[uint8](0x48)
  OCR1BH* = MappedIoRegister[uint8](0x49)
  OCR1A*  = MappedIoRegister[uint16](0x4A)
  OCR1AL* = MappedIoRegister[uint8](0x4A)
  OCR1AH* = MappedIoRegister[uint8](0x4B)
  TCNT1*  = MappedIoRegister[uint16](0x4C)
  TCNT1L* = MappedIoRegister[uint8](0x4C)
  TCNT1H* = MappedIoRegister[uint8](0x4D)
  TCCR1B* = MappedIoRegister[uint8](0x4E)
  TCCR1A* = MappedIoRegister[uint8](0x4F)
  TCCR0A* = MappedIoRegister[uint8](0x50)
  OSCCAL* = MappedIoRegister[uint8](0x51)
  TCNT0*  = MappedIoRegister[uint8](0x52)
  TCCR0B* = MappedIoRegister[uint8](0x53)
  MCUSR*  = MappedIoRegister[uint8](0x54)
  MCUCR*  = MappedIoRegister[uint8](0x55)
  OCR0A*  = MappedIoRegister[uint8](0x56)
  SPMCSR* = MappedIoRegister[uint8](0x57)
  TIFR*   = MappedIoRegister[uint8](0x58)
  TIMSK*  = MappedIoRegister[uint8](0x59)
  GIFR*   = MappedIoRegister[uint8](0x5A)
  GIMSK*  = MappedIoRegister[uint8](0x5B)
  OCR0B*  = MappedIoRegister[uint8](0x5C)
  SPL*    = MappedIoRegister[uint8](0x5D)
  SREG*   = MappedIoRegister[uint8](0x5F)

const
  porta* = Port(direction: DDRA, output: PORTA, input: PINA)
  portb* = Port(direction: DDRB, output: PORTB, input: PINB)
  portd* = Port(direction: DDRD, output: PORTD, input: PIND)

