include mapped_io
include usart
include timer

const
  TCCR1E* = MappedIoRegister[uint8](0x20)
  DIDR0*  = MappedIoRegister[uint8](0x21)
  DIDR1*  = MappedIoRegister[uint8](0x22)
  ADCSRB* = MappedIoRegister[uint8](0x23)
  ADC*    = MappedIoRegister[uint16](0x24)
  ADCL*   = MappedIoRegister[uint8](0x24)
  ADCH*   = MappedIoRegister[uint8](0x25)
  ADCSRA* = MappedIoRegister[uint8](0x26)
  ADMUX*  = MappedIoRegister[uint8](0x27)
  ACSRA*  = MappedIoRegister[uint8](0x28)
  ACSRB*  = MappedIoRegister[uint8](0x29)
  GPIOR0* = MappedIoRegister[uint8](0x2A)
  GPIOR1* = MappedIoRegister[uint8](0x2B)
  GPIOR2* = MappedIoRegister[uint8](0x2C)
  USICR*  = MappedIoRegister[uint8](0x2D)
  USISR*  = MappedIoRegister[uint8](0x2E)
  USIDR*  = MappedIoRegister[uint8](0x2F)
  USIBR*  = MappedIoRegister[uint8](0x30)
  USIPP*  = MappedIoRegister[uint8](0x31)
  OCR0B*  = MappedIoRegister[uint8](0x32)
  OCR0A*  = MappedIoRegister[uint8](0x33)
  TCNT0H* = MappedIoRegister[uint8](0x34)
  TCCR0A* = MappedIoRegister[uint8](0x35)
  PINB*   = MappedIoRegister[uint8](0x36)
  DDRB*   = MappedIoRegister[uint8](0x37)
  PORTB*  = MappedIoRegister[uint8](0x38)
  PINA*   = MappedIoRegister[uint8](0x39)
  DDRA*   = MappedIoRegister[uint8](0x3A)
  PORTA*  = MappedIoRegister[uint8](0x3B)
  EECR*   = MappedIoRegister[uint8](0x3C)
  EEDR*   = MappedIoRegister[uint8](0x3D)
  EEAR*   = MappedIoRegister[uint16](0x3E)
  EEARL*  = MappedIoRegister[uint8](0x3E)
  EEARH*  = MappedIoRegister[uint8](0x3F)
  DWDR*   = MappedIoRegister[uint8](0x40)
  WDTCR*  = MappedIoRegister[uint8](0x41)
  PCMSK1* = MappedIoRegister[uint8](0x42)
  PCMSK0* = MappedIoRegister[uint8](0x43)
  DT1*    = MappedIoRegister[uint8](0x44)
  TC1H*   = MappedIoRegister[uint8](0x45)
  TCCR1D* = MappedIoRegister[uint8](0x46)
  TCCR1C* = MappedIoRegister[uint8](0x47)
  CLKPR*  = MappedIoRegister[uint8](0x48)
  PLLCSR* = MappedIoRegister[uint8](0x49)
  OCR1D*  = MappedIoRegister[uint8](0x4A)
  OCR1C*  = MappedIoRegister[uint8](0x4B)
  OCR1B*  = MappedIoRegister[uint8](0x4C)
  OCR1A*  = MappedIoRegister[uint8](0x4D)
  TCNT1*  = MappedIoRegister[uint8](0x4E)
  TCCR1B* = MappedIoRegister[uint8](0x4F)
  TCCR1A* = MappedIoRegister[uint8](0x50)
  OSCCAL* = MappedIoRegister[uint8](0x51)
  TCNT0L* = MappedIoRegister[uint8](0x52)
  TCCR0B* = MappedIoRegister[uint8](0x53)
  MCUSR*  = MappedIoRegister[uint8](0x54)
  MCUCR*  = MappedIoRegister[uint8](0x55)
  PRR*    = MappedIoRegister[uint8](0x56)
  SPMCSR* = MappedIoRegister[uint8](0x57)
  TIFR*   = MappedIoRegister[uint8](0x58)
  TIMSK*  = MappedIoRegister[uint8](0x59)
  GIFR*   = MappedIoRegister[uint8](0x5A)
  GIMSK*  = MappedIoRegister[uint8](0x5B)
  SP*     = MappedIoRegister[uint16](0x5D)
  SPL*    = MappedIoRegister[uint8](0x5D)
  SPH*    = MappedIoRegister[uint8](0x5E)
  SREG*   = MappedIoRegister[uint8](0x5F)

const
  porta* = Port(direction: DDRA, output: PORTA, input: PINA)
  portb* = Port(direction: DDRB, output: PORTB, input: PINB)

