include mapped_io
include usart
include timer

const
  ADCSRB* = MappedIoRegister[uint8](0x23)
  ADC*    = MappedIoRegister[uint16](0x24)
  ADCL*   = MappedIoRegister[uint8](0x24)
  ADCH*   = MappedIoRegister[uint8](0x25)
  ADCSRA* = MappedIoRegister[uint8](0x26)
  ADMUX*  = MappedIoRegister[uint8](0x27)
  ACSR*   = MappedIoRegister[uint8](0x28)
  USICR*  = MappedIoRegister[uint8](0x2D)
  USISR*  = MappedIoRegister[uint8](0x2E)
  USIDR*  = MappedIoRegister[uint8](0x2F)
  USIBR*  = MappedIoRegister[uint8](0x30)
  GPIOR0* = MappedIoRegister[uint8](0x31)
  GPIOR1* = MappedIoRegister[uint8](0x32)
  GPIOR2* = MappedIoRegister[uint8](0x33)
  DIDR0*  = MappedIoRegister[uint8](0x34)
  PCMSK*  = MappedIoRegister[uint8](0x35)
  PINB*   = MappedIoRegister[uint8](0x36)
  DDRB*   = MappedIoRegister[uint8](0x37)
  PORTB*  = MappedIoRegister[uint8](0x38)
  EECR*   = MappedIoRegister[uint8](0x3C)
  EEDR*   = MappedIoRegister[uint8](0x3D)
  EEAR*   = MappedIoRegister[uint16](0x3E)
  EEARL*  = MappedIoRegister[uint8](0x3E)
  EEARH*  = MappedIoRegister[uint8](0x3F)
  PRR*    = MappedIoRegister[uint8](0x40)
  WDTCR*  = MappedIoRegister[uint8](0x41)
  DWDR*   = MappedIoRegister[uint8](0x42)
  DTPS*   = MappedIoRegister[uint8](0x43)
  DT1B*   = MappedIoRegister[uint8](0x44)
  DT1A*   = MappedIoRegister[uint8](0x45)
  CLKPR*  = MappedIoRegister[uint8](0x46)
  PLLCSR* = MappedIoRegister[uint8](0x47)
  OCR0B*  = MappedIoRegister[uint8](0x48)
  OCR0A*  = MappedIoRegister[uint8](0x49)
  TCCR0A* = MappedIoRegister[uint8](0x4A)
  OCR1B*  = MappedIoRegister[uint8](0x4B)
  GTCCR*  = MappedIoRegister[uint8](0x4C)
  OCR1C*  = MappedIoRegister[uint8](0x4D)
  OCR1A*  = MappedIoRegister[uint8](0x4E)
  TCNT1*  = MappedIoRegister[uint8](0x4F)
  TCCR1*  = MappedIoRegister[uint8](0x50)
  OSCCAL* = MappedIoRegister[uint8](0x51)
  TCNT0*  = MappedIoRegister[uint8](0x52)
  TCCR0B* = MappedIoRegister[uint8](0x53)
  MCUSR*  = MappedIoRegister[uint8](0x54)
  MCUCR*  = MappedIoRegister[uint8](0x55)
  SPMCSR* = MappedIoRegister[uint8](0x57)
  TIFR*   = MappedIoRegister[uint8](0x58)
  TIMSK*  = MappedIoRegister[uint8](0x59)
  GIFR*   = MappedIoRegister[uint8](0x5A)
  GIMSK*  = MappedIoRegister[uint8](0x5B)
  SP*     = MappedIoRegister[uint16](0x5D)
  SPL*    = MappedIoRegister[uint8](0x5D)
  SPH*    = MappedIoRegister[uint8](0x5E)
  SREG*   = MappedIoRegister[uint8](0x5F)

const
  portb* = Port(direction: DDRB, output: PORTB, input: PINB)

