include mapped_io
include usart
include timer

const
  PINA*   = MappedIoRegister[uint8](0x0)
  DDRA*   = MappedIoRegister[uint8](0x1)
  PORTA*  = MappedIoRegister[uint8](0x2)
  PUEA*   = MappedIoRegister[uint8](0x3)
  PINB*   = MappedIoRegister[uint8](0x4)
  DDRB*   = MappedIoRegister[uint8](0x5)
  PORTB*  = MappedIoRegister[uint8](0x6)
  PUEB*   = MappedIoRegister[uint8](0x7)
  PORTCR* = MappedIoRegister[uint8](0x8)
  PCMSK0* = MappedIoRegister[uint8](0x9)
  PCMSK1* = MappedIoRegister[uint8](0xA)
  GIFR*   = MappedIoRegister[uint8](0xB)
  GIMSK*  = MappedIoRegister[uint8](0xC)
  DIDR0*  = MappedIoRegister[uint8](0xD)
  ADC*    = MappedIoRegister[uint16](0xE)
  ADCL*   = MappedIoRegister[uint8](0xE)
  ADCH*   = MappedIoRegister[uint8](0xF)
  ADMUX*  = MappedIoRegister[uint8](0x10)
  ADCSRB* = MappedIoRegister[uint8](0x11)
  ADCSRA* = MappedIoRegister[uint8](0x12)
  ACSRB*  = MappedIoRegister[uint8](0x13)
  ACSRA*  = MappedIoRegister[uint8](0x14)
  OCR0B*  = MappedIoRegister[uint8](0x15)
  OCR0A*  = MappedIoRegister[uint8](0x16)
  TCNT0*  = MappedIoRegister[uint8](0x17)
  TCCR0B* = MappedIoRegister[uint8](0x18)
  TCCR0A* = MappedIoRegister[uint8](0x19)
  ICR1*   = MappedIoRegister[uint16](0x1A)
  ICR1L*  = MappedIoRegister[uint8](0x1A)
  ICR1H*  = MappedIoRegister[uint8](0x1B)
  OCR1B*  = MappedIoRegister[uint16](0x1C)
  OCR1BL* = MappedIoRegister[uint8](0x1C)
  OCR1BH* = MappedIoRegister[uint8](0x1D)
  OCR1A*  = MappedIoRegister[uint16](0x1E)
  OCR1AL* = MappedIoRegister[uint8](0x1E)
  OCR1AH* = MappedIoRegister[uint8](0x1F)
  TCNT1*  = MappedIoRegister[uint16](0x20)
  TCNT1L* = MappedIoRegister[uint8](0x20)
  TCNT1H* = MappedIoRegister[uint8](0x21)
  TCCR1C* = MappedIoRegister[uint8](0x22)
  TCCR1B* = MappedIoRegister[uint8](0x23)
  TCCR1A* = MappedIoRegister[uint8](0x24)
  TIFR*   = MappedIoRegister[uint8](0x25)
  TIMSK*  = MappedIoRegister[uint8](0x26)
  GTCCR*  = MappedIoRegister[uint8](0x27)
  TWSD*   = MappedIoRegister[uint8](0x28)
  TWSAM*  = MappedIoRegister[uint8](0x29)
  TWSA*   = MappedIoRegister[uint8](0x2A)
  TWSSRA* = MappedIoRegister[uint8](0x2B)
  TWSCRB* = MappedIoRegister[uint8](0x2C)
  TWSCRA* = MappedIoRegister[uint8](0x2D)
  SPDR*   = MappedIoRegister[uint8](0x2E)
  SPSR*   = MappedIoRegister[uint8](0x2F)
  SPCR*   = MappedIoRegister[uint8](0x30)
  WDTCSR* = MappedIoRegister[uint8](0x31)
  NVMCSR* = MappedIoRegister[uint8](0x32)
  NVMCMD* = MappedIoRegister[uint8](0x33)
  PRR*    = MappedIoRegister[uint8](0x35)
  CLKPSR* = MappedIoRegister[uint8](0x36)
  CLKMSR* = MappedIoRegister[uint8](0x37)
  OSCCAL* = MappedIoRegister[uint8](0x39)
  MCUCR*  = MappedIoRegister[uint8](0x3A)
  RSTFLR* = MappedIoRegister[uint8](0x3B)
  CCP*    = MappedIoRegister[uint8](0x3C)
  SP*     = MappedIoRegister[uint16](0x3D)
  SPL*    = MappedIoRegister[uint8](0x3D)
  SPH*    = MappedIoRegister[uint8](0x3E)
  SREG*   = MappedIoRegister[uint8](0x3F)

const
  portb* = Port(direction: DDRB, output: PORTB, input: PINB)
  porta* = Port(direction: DDRA, output: PORTA, input: PINA)

